export const list = {
  data: [
    {
      orderId: 444287,
      channel: 75,
      channelName: 'API-包钢',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司 ',
      contactName: '徐云',
      salesName: 'cathytraining',
      amount: 3.67,
      createdTime: '2021-10-19T10:35:01',
      syncTime: '2022-03-30T13:54:57',
      lines: [
        {
          orderItemId: '104739119',
          lineNum: 1,
          sku: '1A6781',
          itemDesc: '1500#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 1,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444161,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 45.54,
      createdTime: '2021-09-29T15:17:51',
      syncTime: '2021-09-29T15:20:44',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: 'FA039945',
          itemDesc: 'THERMOVAC全新原裝正品真空計',
          Qty: 1,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444160,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 45.54,
      createdTime: '2021-09-29T15:16:34',
      syncTime: '2021-09-29T15:20:42',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: 'FA039956',
          itemDesc: 'FOTEK 固态继电器',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444159,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 704.88,
      createdTime: '2021-09-29T15:13:17',
      syncTime: '2022-02-22T10:00:30',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '3B1704',
          itemDesc: '派克乐可利标准型气枪，10pcs/盒',
          Qty: 1,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 1,
          sku: '1P7380',
          itemDesc: '本白涤棉纱线手套，600g/打，红色包边，22cm',
          Qty: 10,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 2,
          sku: '1F5672',
          itemDesc: '管塞EPP4 适用接管外径4mm',
          Qty: 50,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 3,
          sku: '1F5674',
          itemDesc: '管塞EPP8 适用接管外径8mm',
          Qty: 20,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 4,
          sku: '1C3098',
          itemDesc: 'PT1/4" 二位五通单电控阀4V210-08-DC24V,内部先导式',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 5,
          sku: '1B8929',
          itemDesc: '六角螺母 碳钢 蓝白锌 8级 DIN934 M4 1000个',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 6,
          sku: '1D2544',
          itemDesc: 'PU气管（透明）4X2 长度100m',
          Qty: 1,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444158,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 45.54,
      createdTime: '2021-09-29T14:56:37',
      syncTime: '2021-09-29T15:00:42',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1C2628',
          itemDesc: 'F3 刀片 用于切钢管',
          Qty: 2,
          BizStatus: 21,
          dropShipFlag: false,
          salesMoq: 0,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444125,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 2465.1,
      createdTime: '2021-09-24T17:11:04',
      syncTime: '2021-09-24T17:15:58',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 1,
          sku: '1B0124',
          itemDesc: '低压高分断能力熔断器，NT1-250',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 2,
          sku: '1B0125',
          itemDesc: '低压高分断能力熔断器，NT2-125',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 3,
          sku: '1B0126',
          itemDesc: '低压高分断能力熔断器，NT2-160',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 4,
          sku: '1B0127',
          itemDesc: '低压高分断能力熔断器，NT2-200',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 5,
          sku: '1B0123',
          itemDesc: '低压高分断能力熔断器，NT1-224',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 6,
          sku: '1B0128',
          itemDesc: '低压高分断能力熔断器，NT2-224',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 7,
          sku: '1B0129',
          itemDesc: '低压高分断能力熔断器，NT2-250',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 8,
          sku: '1B0130',
          itemDesc: '低压高分断能力熔断器，NT2-300',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 9,
          sku: '1B0121',
          itemDesc: '低压高分断能力熔断器，NT1-160',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 10,
          sku: '1H8090',
          itemDesc: '3M EAR 312-1250 高降噪子弹型耳塞',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444119,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 1232.55,
      createdTime: '2021-09-24T11:06:04',
      syncTime: '2021-09-24T11:10:58',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 1,
          sku: '1B0124',
          itemDesc: '低压高分断能力熔断器，NT1-250',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 2,
          sku: '1B0125',
          itemDesc: '低压高分断能力熔断器，NT2-125',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 3,
          sku: '1B0126',
          itemDesc: '低压高分断能力熔断器，NT2-160',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 4,
          sku: '1B0127',
          itemDesc: '低压高分断能力熔断器，NT2-200',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 5,
          sku: '1B0123',
          itemDesc: '低压高分断能力熔断器，NT1-224',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 6,
          sku: '1B0128',
          itemDesc: '低压高分断能力熔断器，NT2-224',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 7,
          sku: '1B0129',
          itemDesc: '低压高分断能力熔断器，NT2-250',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 8,
          sku: '1B0130',
          itemDesc: '低压高分断能力熔断器，NT2-300',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 9,
          sku: '1B0121',
          itemDesc: '低压高分断能力熔断器，NT1-160',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: null,
          lineNum: 10,
          sku: '1H8090',
          itemDesc: '3M EAR 312-1250 高降噪子弹型耳塞',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444057,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 113.85,
      createdTime: '2021-09-18T16:58:16',
      syncTime: '2022-02-22T09:59:57',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 5,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 444053,
      channel: 80,
      channelName: 'NC',
      customerCode: 'A1010',
      customerName: '广州盖盟达工业互联网科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 0,
      createdTime: '2021-09-18T14:31:34',
      syncTime: null,
      lines: [],
    },
    {
      orderId: 444048,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 0,
      createdTime: '2021-09-18T11:10:27',
      syncTime: null,
      lines: [],
    },
    {
      orderId: 443819,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 68.31,
      createdTime: '2021-09-07T14:34:57',
      syncTime: '2021-09-07T14:39:53',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 3,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443817,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司 ',
      contactName: 'NICOLE YU',
      salesName: 'cathytraining',
      amount: 84,
      createdTime: '2021-09-07T13:48:41',
      syncTime: '2021-09-07T13:49:54',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 3,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443816,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司 ',
      contactName: 'NICOLE YU',
      salesName: 'cathytraining',
      amount: 61,
      createdTime: '2021-09-07T13:44:51',
      syncTime: '2021-09-07T13:49:53',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443815,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司 ',
      contactName: 'NICOLE YU',
      salesName: 'cathytraining',
      amount: 275,
      createdTime: '2021-09-07T13:32:07',
      syncTime: '2021-09-07T13:39:53',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1H8090',
          itemDesc: '3M EAR 312-1250 高降噪子弹型耳塞',
          Qty: 1,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: '',
          lineNum: 1,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 7,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443814,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司 ',
      contactName: 'NICOLE YU',
      salesName: 'cathytraining',
      amount: 328,
      createdTime: '2021-09-07T13:27:03',
      syncTime: '2021-09-07T13:34:53',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 5,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: '',
          lineNum: 1,
          sku: '1H8090',
          itemDesc: '3M EAR 312-1250 高降噪子弹型耳塞',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 1,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443681,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司',
      contactName: '徐云',
      salesName: 'lucyfang',
      amount: 199,
      createdTime: '2021-09-02T14:54:39',
      syncTime: '2021-09-02T17:14:53',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 8,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443667,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: '徐云',
      salesName: '',
      amount: 0,
      createdTime: '2021-09-02T12:48:58',
      syncTime: '2021-09-02T12:49:53',
      lines: [],
    },
    {
      orderId: 443657,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司',
      contactName: '徐云',
      salesName: 'lucyfang',
      amount: 71.5,
      createdTime: '2021-09-02T10:24:32',
      syncTime: '2021-09-02T10:41:03',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6783',
          itemDesc: '1500#无铅电工胶带 18MM X 10M 黄色',
          Qty: 3,
          BizStatus: 11,
          dropShipFlag: true,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: '',
          lineNum: 1,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443655,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司',
      contactName: '徐云',
      salesName: 'lucyfang',
      amount: 115.56,
      createdTime: '2021-09-02T10:18:52',
      syncTime: '2021-09-02T10:41:00',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 4,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
        {
          orderItemId: '',
          lineNum: 1,
          sku: '1A6782',
          itemDesc: '1500#无铅电工胶带 18MM X 10M 红色',
          Qty: 2,
          BizStatus: 11,
          dropShipFlag: true,
          salesMoq: 1,
          salesMoqIncrement: 1,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443653,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司',
      contactName: '徐云',
      salesName: 'lucyfang',
      amount: 87.45,
      createdTime: '2021-09-02T09:02:47',
      syncTime: '2021-09-02T10:05:57',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 3,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443637,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: '徐云',
      salesName: '',
      amount: 250.47,
      createdTime: '2021-09-01T17:57:26',
      syncTime: '2021-09-01T18:07:13',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 11,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443631,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: '徐云',
      salesName: '',
      amount: 1776.06,
      createdTime: '2021-09-01T16:48:14',
      syncTime: '2021-09-01T16:49:24',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 78,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443630,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: '徐云',
      salesName: '',
      amount: 5100.48,
      createdTime: '2021-09-01T16:32:41',
      syncTime: '2021-09-01T16:34:24',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 224,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443619,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: 'nosales',
      salesName: '',
      amount: 159.39,
      createdTime: '2021-09-01T14:22:13',
      syncTime: '2021-09-01T14:25:36',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 7,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443615,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司',
      contactName: '徐云',
      salesName: 'lucyfang',
      amount: 176,
      createdTime: '2021-09-01T13:54:10',
      syncTime: '2021-09-01T14:00:36',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 7,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443556,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: '徐云',
      salesName: '',
      amount: 1684.98,
      createdTime: '2021-08-31T10:20:43',
      syncTime: '2021-08-31T10:25:36',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 74,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443552,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: '徐云',
      salesName: '',
      amount: 1092.96,
      createdTime: '2021-08-30T21:45:38',
      syncTime: '2021-08-30T21:50:38',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 48,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443549,
      channel: 80,
      channelName: 'NC',
      customerCode: '1120',
      customerName: '广州盖盟达信息科技有限公司',
      contactName: '徐云',
      salesName: '',
      amount: 1024.65,
      createdTime: '2021-08-30T21:34:44',
      syncTime: '2021-08-30T21:35:36',
      lines: [
        {
          orderItemId: null,
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 45,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443547,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600000012',
      customerName: '柯马（上海）工程有限公司',
      contactName: '徐云',
      salesName: 'lucyfang',
      amount: 1035,
      createdTime: '2021-08-30T21:07:24',
      syncTime: '2021-08-30T21:20:36',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 45,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
    {
      orderId: 443545,
      channel: 10,
      channelName: 'OMS',
      customerCode: '0600043554',
      customerName: '利莱森玛电机科技（福州）有限公司',
      contactName: '陈慧敏*',
      salesName: 'alinachen',
      amount: 1422,
      createdTime: '2021-08-30T20:55:20',
      syncTime: '2021-08-30T21:05:47',
      lines: [
        {
          orderItemId: '',
          lineNum: 0,
          sku: '1A6781',
          itemDesc: '1600#无铅电工绝缘胶带 18MM X 10M 黑色',
          Qty: 61,
          BizStatus: 11,
          dropShipFlag: false,
          salesMoq: 2,
          salesMoqIncrement: 0,
          sapBizStatus: 0,
          sapDropShipFlag: false,
          sapSalesMoq: 0,
          sapSalesMoqIncrement: 0,
          errorMessage: null,
        },
      ],
    },
  ],
  total: 30,
  current: 1,
  pageSize: 10,
  success: true,
};
